# Analyzing Worldwide Cancer Data

Fonte dados legal: https://ourworldindata.org/cancer

In [11]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import os

directory = '../data'

# Load the Worldwide Cancer Data into a Pandas data frame
cancer_data = pd.read_csv(f'{directory}/Global cancer incidence in women.csv')

cancer_data.head()

   Unnamed: 0  Rank         Cancer  New cases in 2020  % of all cancers
0           0   NaN   All cancers*            8751759               NaN
1           1   1.0         Breast            2261419              25.8
2           2   2.0  Colorectal **             865630               9.9
3           3   3.0           Lung             770828               8.8
4           4   4.0   Cervix uteri             604127               6.9

In [12]:
cancer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         31 non-null     int64
 1   Rank               30 non-null     float64
 2   Cancer             31 non-null     object
 3   New cases in 2020  31 non-null     int64
 4   % of all cancers   30 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 1.3+ KB

In [13]:
cancer_data.describe()

       Unnamed: 0       Rank  New cases in 2020  % of all cancers
count   31.000000  30.000000       3.100000e+01         30.000000
mean    15.000000  15.500000       5.492260e+05          3.146667
std      9.092121   8.803408       1.581724e+06          4.983887
min      0.000000   1.000000       9.310000e+03          0.100000
25%      7.500000   8.250000       3.554450e+04          0.400000
50%     15.000000  15.500000       1.507910e+05          1.650000
75%     22.500000  22.750000       3.417695e+05          3.475000
max     30.000000  30.000000       8.751759e+06         25.800000

In [14]:
# remove the column Unnamed: 0 -> its the same as the index
cancer_data.drop('Unnamed: 0', axis=1, inplace=True)
cancer_data.describe()

            Rank  New cases in 2020  % of all cancers
count  30.000000       3.100000e+01         30.000000
mean   15.500000       5.492260e+05          3.146667
std     8.803408       1.581724e+06          4.983887
min     1.000000       9.310000e+03          0.100000
25%     8.250000       3.554450e+04          0.400000
50%    15.500000       1.507910e+05          1.650000
75%    22.750000       3.417695e+05          3.475000
max    30.000000       8.751759e+06         25.800000